
version: '2'

services:
  nginx:
    image: nginx
    container_name: "laravel-nginx"
    ports:
      - "8080:80"
    volumes:
      - ./nginx/default.conf:/etc/nginx/conf.d/default.conf
      - ./src/public:/var/www/src/public
    depends_on:
      - php
  php:
    build: ./php
    container_name: "laravel-php"
    working_dir: /src
    volumes:
      - ./src:/var/www/src
    depends_on:
      - db
  db:
    image: mysql:5.7
    container_name: "laravel-mysql"
    restart: always
    ports:
      - 13306:3306
    environment:
      MYSQL_DATABASE: laravel-react
      MYSQL_ROOT_PASSWORD: root
